build/gen-jenkins.sh, instances/technology.dash/target/Dockerfile, instances/technology.dash/target/config.json, instances/technology.dash/target/jenkins/configuration.yml, instances/technology.dash/target/jenkins/title.js, instances/technology.dash/target/k8s/configmap-jenkins-config.yml, instances/technology.dash/target/k8s/statefulset.yml, templates/docker/Dockerfile.hbs, templates/jenkins/configuration.yml.hbs
Working example can be seen at https://ci.eclipse.org/dash/
=> Change the website title to include the display name

incubation/create_new_jiro_jipp.sh, jenkins-new-instance.sh
add a question to create_new_jiro_jipp.sh to decide if ci-staging or ci should be used
=> Deploy to ci.eclipse.org by default

instances/technology.openj9/jenkins/configuration.yml, instances/technology.openj9/jenkins/plugins-list
=> OpenJ9: Add plugin slack

instances/technology.openj9/jenkins/configuration.yml
=> OpenJ9: Add 3 OSX 10.14 instances hosted at UNB

instances/technology.openj9/jenkins/configuration.yml
Added new Aarch64 machine running CentOS7 to Jenkins.
Machine is from packet.net.
Signed-off-by: Colton Mills <millscolt3@gmail.com>
=> Added Cent7 Aarch64 machine

instances/technology.openj9/jenkins/configuration.yml
=> OpenJ9: Update label to match osx 10.14 os

instances/technology.openj9/jenkins/configuration.yml
Aarch64 machine was recently added, but with improper IP address. The IP address has been
updated and should work properly now.
Follow up from #41
Signed-off-by: Colton Mills <millscolt3@gmail.com>
=> Fixed IP address of Aarch64 machine

instances/technology.jgit/jenkins/plugins-list
https://github.com/jenkinsci/git-forensics-plugin
=> Install git-forensics plugin for JGit JIPP

instances/technology.openj9/jenkins/plugins-list
- Needed for jobs using REST API calls
=> OpenJ9: Add http_request plugin

instances/technology.openj9/jenkins/configuration.yml
- Related https://bugs.eclipse.org/bugs/show_bug.cgi?id=550740#c15
=> Update OpenJ9 Github API Token Cred ID

instances/technology.openj9/jenkins/plugins-list
Add build with parameters plugin to the Openj9 Jenkins instance
Signed-off-by: smlambert <slambert@gmail.com>
=> Add build with parameters plugin

instances/technology.openj9/jenkins/plugins-list
Signed-off-by: smlambert <slambert@gmail.com>
=> Add xvfb plugin to support openjdk awt/swing tests

instances/technology.openj9/jenkins/configuration.yml
* newer git packages have a dependency on libraries not included on the
system paths
=> Modify LIBPATH to include freeware paths on AIX 7.1.5

templates/k8s/statefulset.yml.hbs
See https://github.com/jenkinsci/extras-executable-war/#jetty-session-ids
=> Bug 552465 - Specify instance-specific harcoded name for session id cookie name

instances/technology.openj9/jenkins/configuration.yml
=> Adding AIX Systems 7-10 to OpenJ9

instances/technology.openj9/jenkins/configuration.yml
=> Update OSX instances as ip addresses changed with UNB power down

instances/technology.openj9/jenkins/configuration.yml
=> Modify UNB connection details to resolve on the proxy

instances/technology.openj9/jenkins/configuration.yml
=> Removing space from connection details for osx1014-x86-1

instances/technology.openj9/jenkins/configuration.yml
=> Update UNB power8 machine ips

instances/ee4j.glassfish/config.jsonnet, instances/ee4j.jaf/config.jsonnet, instances/ee4j.jakartaee-platform/config.jsonnet, instances/ee4j.jakartaee-tck/config.jsonnet, instances/ee4j.mail/config.jsonnet
Re: https://bugs.eclipse.org/bugs/show_bug.cgi?id=558054
Thanks for the tip!
P.S.  Please restart instances after applying the change.
=> Switched some projects to use quicksilver-light theme to avoid reverse video console output

instances/technology.openj9/jenkins/configuration.yml
* disable existing z14 machines as they need to be returned by years end
=> Add 4 z15 Marist machines

instances/technology.openj9/jenkins/configuration.yml
* disable z15 until known issues can be resolved
=> Restore z14 zlinux instances to service

instances/polarsys.capella/jenkins/plugins-list
Change-Id: Ia18da91bf889ba8e8f726351782bc666bff83e52
Signed-off-by: Philippe DUL <philippe.dul@thalesgroup.com>
=> Add pipeline-github plugin for Eclipse Capella Jenkins

instances/technology.openj9/jenkins/configuration.yml
=> Remove z14 390 machines from use, rename z15 machines 5-8 to 1-4

instances/technology.openj9/jenkins/configuration.yml
=> OpenJ9: Add z15 label to 390 machines

instances/technology.openj9/jenkins/configuration.yml
=> OpenJ9: Temp remove build label from aix-1

instances/technology.openj9/jenkins/configuration.yml
=> OpenJ9: Add TEMP env var for Windows machines

instances/tools.gef/jenkins/plugins-list
Signed-off-by: Nico Prediger <mail@nicoprediger.de>
=> Add plugins to GEF Jenkins

instances/technology.openj9/jenkins/configuration.yml
=> OpenJ9: Change labels and names on latest 390 machine additions

instances/technology.openj9/jenkins/configuration.yml
* update ip address change for aix71-p8-6
=> OpenJ9: AIX and PPCLE machine updates

instances/technology.openj9/jenkins/configuration.yml
* rename existing cent7p8j91 -> cent7-ppcle-1 to match naming conventions
=> OpenJ9: Machine additions and updates

instances/technology.openj9/jenkins/configuration.yml
=> OpenJ9: Add 10 replacement AIX 7.1 machines

instances/ecd.codewind/jenkins/configuration.yml
Signed-off-by: Joseph Kim <kjoseph@ca.ibm.com>
=> Bug 561452 - Setup additional Codewind docker-build agents

build/build-image.sh, build/clean-instance.sh, build/gen-config.sh, build/gen-dockerfile.sh, build/gen-jenkins.sh, build/gen-k8s.sh, build/gen-mvn-settings.sh, build/gen-permissions.sh, build/gen-yaml.sh, build/k8s-delete.sh, build/k8s-deploy.sh, build/merge-json.sh, build/nexus-pro-token.sh
=> Add minimal documentation for build scripts

instances/technology.openj9/jenkins/configuration.yml
* [skip ci]
* eclipse/openj9#9474
=> OpenJ9: Add cmake v3.17 to PATH

instances/technology.openj9/jenkins/configuration.yml
=> OpenJ9: Add test label to cent7-p machines

templates/k8s/m2-dir.libsonnet
See https://bugs.eclipse.org/bugs/show_bug.cgi?id=560161 for details
=> Bug 560161 - Various improvements to default toolchains.xml

instances/technology.openj9/jenkins/configuration.yml
=> OpenJ9: Change to default java on ub16-ppcle-3

instances/technology.openj9/jenkins/configuration.yml
=> OpenJ9: Adding 6 cent7 x Machines

instances/technology.openj9/jenkins/configuration.yml
=> [OpenJ9] Add docker label to new Cent7 x nodes

instances/technology.openj9/jenkins/configuration.yml
=> OpenJ9: Add build labels to osx 10.14 systems

jenkins-create-credentials-token.sh, jenkins-create-credentials.sh
Should those scripts be put in a sub-folder?
=> Automate creation of Jenkins credentials

instances/technology.openj9/jenkins/configuration.yml
=> Adding new win2012 machine

instances/technology.openj9/jenkins/configuration.yml
=> OpenJ9: Removing Older Winx86 Machines

instances/eclipse.platform.releng/jenkins/configuration.yml
=> Updated ta9y0-macos agent configuration

instances/ee4j.openmq/jenkins/plugins-list
https://plugins.jenkins.io/jacoco/
=> Add 'jacoco' plugin to OpenMQ Jenkins

instances/polarsys.capella/jenkins/plugins-list
Change-Id: I24479784b5a24ae1782fec6e714ca8dc7c04f75d
Signed-off-by: Philippe DUL <philippe.dul@thalesgroup.com>
=> Add pipeline-utility-steps plugin for Eclipse Capella JIPP

instances/technology.openj9/jenkins/configuration.yml
Also cleanup some whitespace
Eclipse Bugzilla 568882
=> OpenJ9: Update credential ID to new human-readable

instances/eclipse.platform.releng/jenkins/configuration.yml
Added aarm64 machines
Signed-off-by: Sravan Kumar Lakkimsetti <sravankumarl@in.ibm.com>
=> Updated configuration.yml

instances/technology.openj9/jenkins/configuration.yml
=> OpenJ9: Add UNB artifactory node for automated monitoring and cleaning

instances/technology.omr/jenkins/configuration.yml
=> [OMR] Add CROSS_SYSROOT_RISCV64 env var to deb10 machine

debug/show-mvn-credentials.sh
Signed-off-by: Frederic Gurr <frederic.gurr@eclipse-foundation.org>
=> Fix issue with multiple settings.xml files

build/gen-config.sh, build/gen-sbt-properties.sh, templates/clouds.libsonnet, templates/config.libsonnet, templates/jenkins/configuration.yml.hbs, templates/jiro_phase2.libsonnet, templates/k8s/sbt-secret-dir.libsonnet
Signed-off-by: Frederic Gurr <frederic.gurr@eclipse-foundation.org>
=> Support sbt config folder

instances/technology.openj9/config.jsonnet
New requirement via AdoptOpenJDK/openjdk-tests#2375
=> OpenJ9: Add parameter-separator plugin

documentation.md
Signed-off-by: Frederic Gurr <frederic.gurr@eclipse-foundation.org>
=> First stab at adding some documentation

instances/technology.openj9/jenkins/configuration.yml
=> Openj9: Adding 5 WIN2012 x86 Machines

instances/adoptium.temurin-compliance/jenkins/configuration.yml
Signed-off-by: Stewart X Addison <sxa@redhat.com>
=> Update names of AIX systems

instances/technology.omr/jenkins/configuration.yml
=> Add compile label to all omr nodes

instances/technology.omr/jenkins/configuration.yml
* 13 UNB xLinux nodes
* 10 UNB pLinux nodes
* 2 IBM Garage AIX nodes
* 3 UNB MacOSX nodes
=> Modify proxy machine that has VPN access to IBM Garage and UNB nodes

instances/adoptium.temurin-compliance/target/jenkins/plugins-list.txt
FIxes https://github.com/eclipse-cbi/jiro/issues/170
Signed-off-by: Shelley Lambert <slambert@gmail.com>
=> Add xunit plugin to temurin-compliance Jenkins server

instances/adoptium.temurin-compliance/jenkins/configuration.yml
Adding more Linux machines to TCK purposes
Signed-off-by: Stewart X Addison <sxa@redhat.com>
=> adoptium: Add Linux/ppc64le machines to compliance instance

instances/adoptium.temurin-compliance/jenkins/configuration.yml
@mbarbero your ssh key is on both machines, you'll need to swap the ssh key for the jenkins user
=> Add solaris x64 machines

instances/iot.kapua/config.jsonnet, instances/iot.kapua/jenkins/configuration.yml
Add NodeJS plugin to iot.kapua instance, needed to build gitbook files
Signed-off-by: Claudio Mezzasalma <claudio.mezzasalma@eurotech.com>
=> Add nodejs plugin to iot.kapua instance

instances/adoptium.temurin-compliance/jenkins/configuration.yml
New machine (A large one, and I'm not planning to leave it permanently for use on this jenkins as it's too powerful to waste on just running TCK!)
Signed-off-by: Stewart X Addison <sxa@redhat.com>
=> Add new aarch64 machine to temurin-compliance jenkins

instances/technology.omr/jenkins/configuration.yml
=> OMR: Add 2 new V2R4 z/OS systems from Marist

instances/technology.omr/jenkins/configuration.yml
=> OMR: update node user id on new z/OS systems

instances/technology.omr/jenkins/configuration.yml
fyi @AdamBrousseau for your awareness.
=> OMR: Add 2 new OSU AIX machines

instances/technology.omr/jenkins/configuration.yml
=> OMR: Add tool location for git on new AIX machines

instances/technology.omr/jenkins/configuration.yml
=> OMR: Remove 2 IBM Garage AIX guests no longer in use

instances/technology.omr/jenkins/configuration.yml
=> OMR: Update env var git location for z/OS nodes

instances/technology.omr/jenkins/configuration.yml
for running CopyrightCheck job
=> OMR: Add worker label to proxy machine

instances/eclipse.platform/config.jsonnet
This will allow Eclipse Platform to add comments from Jenkinsfile to PRs.
See https://github.com/eclipse-platform/eclipse.platform.resources/pull/11#issuecomment-1080978054
=> Add pipeline-github-plugin to platform CI

instances/ecd.cdt-cloud/config.jsonnet
* embeddable-build-status
* mail-watcher-plugin
* pipeline-utility-steps
=> Add Jenkins Plugins for CDT.Cloud

setup_ubuntu.sh
yq installation doesn't work with my ubuntu version: impish
Not present in yq repo : http://ppa.launchpad.net/rmescandon/yq/ubuntu/dists/
Propose to use binary download via wget.
=> fix: yq installation, print tools version

.github/workflows/github-actions.yml
Add shellcheck control for sh file.
Some "error" are report!!
```
Error: ./migration/convert_agents.sh:133:22: error: > is for string comparisons. Use -gt instead. [SC2071]
Error: ./migration/convert_agents.sh:133:44: error: > is for string comparisons. Use -gt instead. [SC2071]
Error: ./migration/convert_agents.sh:140:22: error: > is for string comparisons. Use -gt instead. [SC2071]
Notice: ./migration/convert_agents.sh:145:21: note: $/${} is unnecessary on arithmetic variables. [SC2004]
Notice: ./migration/convert_agents.sh:147:83: note: Double quote to prevent globbing and word splitting. [SC2086]
Notice: ./migration/convert_agents.sh:149:85: note: Double quote to prevent globbing and word splitting. [SC2086]
Error: ./migration/convert_agents.sh:158:24: error: > is for string …
```
=> feat: add github action for shell control

instances/technology.omr/jenkins/configuration.yml
* eclipse/omr#6501
* replace 10 existing ubuntu16 machines
=> OMR: Add ubuntu 20 x86 machines with cgroup support

instances/technology.omr/jenkins/configuration.yml
=> OMR: Add mac11-aarch64-8

instances/technology.omr/jenkins/configuration.yml
=> OMR: Fix remoteFS dir on amac-8

instances/technology.omr/jenkins/configuration.yml
=> OMR: Update z/os to use default java (11)

instances/tools.cdt/config.jsonnet
Similar to #204 but for tools.cdt
=> Added pipeline-github to tools.cdt

instances/technology.omr/jenkins/configuration.yml
For all the public machines.
Also delete win-1 since it is gone.
=> OMR: Change to ssh launcher for node connections

instances/technology.omr/jenkins/configuration.yml
=> OMR: Add 2 new zLinux servers from Marist

instances/technology.set/config.jsonnet, instances/technology.set/target/config.json, instances/technology.set/target/k8s/limit-range.json, instances/technology.set/target/k8s/resource-quotas.json, instances/technology.set/target/k8s/statefulset.json
https://gitlab.eclipse.org/eclipsefdn/helpdesk/-/issues/2235
=> Assign a resource pack to the Eclipse SET project

instances/ee4j.glassfish/config.jsonnet, instances/ee4j.glassfish/target/config.json, instances/ee4j.glassfish/target/k8s/resource-quotas.json
https://gitlab.eclipse.org/eclipsefdn/helpdesk/-/issues/2102
=> Assign an OmniFish resource pack to the Eclipse GlassFish project

instances/eclipse.platform.releng/jenkins/configuration.yml
=> Issue 2209 Retire https://ci.eclipse.org/releng/computer/ppc64le-build/

instances/technology.omr/jenkins/configuration.yml
* disable dump creation, reduce Xmx
* eclipse-openj9/openj9#16173
=> OMR: Modify java options for shared jenkins node connections

instances/adoptium.temurin-compliance/jenkins/configuration.yml
Add label "sw.os.aix.7_2" to node jck-skytap-aix72-ppc64-3 for issue: https://gitlab.eclipse.org/eclipsefdn/helpdesk/-/issues/2337
Signed-off-by: Andrew Leonard <anleonar@redhat.com>
=> Add sw.os.aix.7_2 label to node jck-skytap-aix72-ppc64-3

instances/adoptium.mc/config.jsonnet
Adds Jenkins plugins needed in order to setup Mission Control builds
=> Additional plugins for mission control build

instances/adoptium.temurin-compliance/jenkins/configuration.yml, instances/adoptium.temurin-compliance/target/jenkins/configuration.yml, instances/adoptium.temurin-compliance/target/k8s/configmap-jenkins-config.yml
Issue https://gitlab.eclipse.org/eclipsefdn/helpdesk/-/issues/2354
=> Agent jck-equinix-containerized-ubuntu2004-aarch32-1 to JDK-11, fix

instances/adoptium.temurin-compliance/jenkins/configuration.yml, instances/adoptium.temurin-compliance/target/jenkins/configuration.yml, instances/adoptium.temurin-compliance/target/k8s/configmap-jenkins-config.yml
Issue #2359 https://gitlab.eclipse.org/eclipsefdn/helpdesk/-/issues/2359
=> AIX and pLinux node agent needs higher JVM heap size

instances/technology.omr/jenkins/configuration.yml
=> Use remoting.jar instead of slave.jar

instances/ecd.glsp/config.jsonnet
- embeddable-build-status
- htmlpublisher
=> Add Jenkins Plugins for GLSP

instances/adoptium.temurin-compliance/jenkins/configuration.yml, instances/adoptium.temurin-compliance/target/jenkins/configuration.yml, instances/adoptium.temurin-compliance/target/k8s/configmap-jenkins-config.yml
Issue https://gitlab.eclipse.org/eclipsefdn/helpdesk/-/issues/2032
=> Upgrade jdk on jck-skytap-aix71-ppc64-2

instances/eclipse.platform.releng/config.jsonnet
https://gitlab.eclipse.org/eclipsefdn/helpdesk/-/issues/2546
@fredg02 could you please review and deploy this?
I just did it like you did if for eclipse.platform in e562016d21ed1e0b83b1144189f9552b34e22d6f
=> Please enable github-checks-plugin for eclipse.platform.releng JIPP

instances/eclipse.pde/config.jsonnet, instances/eclipse.pde/target/config.json, instances/eclipse.pde/target/jenkins/plugins-list.txt, instances/eclipse.pde/target/jenkins/plugins.log
EF issue https://gitlab.eclipse.org/eclipsefdn/helpdesk/-/issues/2920
=> Enable github-checks-plugin for pde.

instances/technology.omr/jenkins/configuration.yml
mac11-aarch64-08 changed in configuration.yml to mac13-aarch64-08
=> Title: OMR changes jenkins conf mac11-aarch64-08

instances/technology.m2e/config.jsonnet, instances/technology.m2e/target/config.json, instances/technology.m2e/target/jenkins/configuration.yml, instances/technology.m2e/target/k8s/configmap-jenkins-config.yml, instances/technology.m2e/target/k8s/limit-range.json, instances/technology.m2e/target/k8s/resource-quotas.json, instances/technology.m2e/target/k8s/statefulset.json
Related to https://gitlab.eclipse.org/eclipsefdn/helpdesk/-/issues/3312
=> Add a new resource pack for m2e

instances/technology.omr/jenkins/configuration.yml
/tmp is small and Jenkins keeps marking these machines offline
=> Set agent tmp to to HOME/tmp

instances/technology.omr/target/jenkins/configuration.yml, instances/technology.omr/target/k8s/configmap-jenkins-config.yml
Related to PR: https://github.com/eclipse-cbi/jiro/pull/290
=> Update OMR target files

instances/technology.tycho/config.jsonnet, instances/technology.tycho/target/config.json, instances/technology.tycho/target/jenkins/configuration.yml, instances/technology.tycho/target/k8s/configmap-jenkins-config.yml, instances/technology.tycho/target/k8s/resource-quotas.json, instances/technology.tycho/target/k8s/statefulset.json
Related to https://gitlab.eclipse.org/eclipsefdn/helpdesk/-/issues/3450
=> Add resource pack to tycho

instances/technology.omr/jenkins/configuration.yml
adds two AIX 7.2 node to jenkins p8-java1-ibm[11,12]
=> OMR adds jenkins conf p8-java1-ibm[11,12]

instances/tools.tracecompass/target/config.json, instances/tools.tracecompass/target/jenkins/plugins.log
Especially re-sync maven-plugin while missing after cleaning plugins dependencies directory.
=> Sync tracecompass to the last jiro-master with maven-plugin

templates/k8s/statefulset.libsonnet
Winstone jar is now located in "executable" sub directory
=> Winstone path on pre-stop

instances/science.ice/target/jenkins/configuration.yml, instances/science.ice/target/k8s/configmap-jenkins-config.yml, instances/science.ice/target/k8s/statefulset.json
EF issue: https://gitlab.eclipse.org/eclipsefdn/helpdesk/-/issues/3926
=> Updates introduced with ossrh regeneration

instances/foundation-internal.webdev/jenkins/configuration.yml, instances/foundation-internal.webdev/target/jenkins/configuration.yml, instances/foundation-internal.webdev/target/jenkins/plugins.log, instances/foundation-internal.webdev/target/k8s/configmap-jenkins-config.yml
https://gitlab.eclipse.org/eclipsefdn/it/releng/jenkins-pipeline-library/-/tags/v0.10.7
Fix introduce bug in repoId var (delete .git)
=> Upgrade releng-pipeline library to v0.10.7

instances/technology.omr/jenkins/configuration.yml
=> OMR: Fix typo in ub20-x64-omr10 node label

instances/eclipse.platform.releng/config.jsonnet, instances/eclipse.platform.releng/target/config.json, instances/eclipse.platform.releng/target/jenkins/plugins-list.txt, instances/eclipse.platform.releng/target/jenkins/plugins.log
Related to https://gitlab.eclipse.org/eclipsefdn/helpdesk/-/issues/4125
=> Add pipeline-utility-steps plugin to releng instance

instances/modeling.epsilon/config.jsonnet, instances/modeling.epsilon/target/config.json, instances/modeling.epsilon/target/jenkins/plugins-list.txt, instances/modeling.epsilon/target/jenkins/plugins.log
EF issue: https://gitlab.eclipse.org/eclipsefdn/helpdesk/-/issues/4227
Already deployed
=> Add lockable-resources to modeling.epsilon.

instances/modeling.sirius/config.jsonnet, instances/modeling.sirius/target/config.json, instances/modeling.sirius/target/jenkins/plugins-list.txt, instances/modeling.sirius/target/jenkins/plugins.log
EF issue: https://gitlab.eclipse.org/eclipsefdn/helpdesk/-/issues/4212
=> Add lockable-resources plugin to modeling.sirius.

jenkins-create-credentials-token.sh
Related to https://gitlab.eclipse.org/eclipsefdn/helpdesk/-/issues/3134
=> Add quay.io

instances/automotive.openpass/jenkins/configuration.yml, instances/automotive.openpass/target/jenkins/configuration.yml, instances/automotive.openpass/target/jenkins/plugins.log, instances/automotive.openpass/target/k8s/configmap-jenkins-config.yml
Related to https://gitlab.eclipse.org/eclipsefdn/helpdesk/-/issues/4168
=> Add windows 10 agent configuration

instances/modeling.sirius/config.jsonnet, instances/modeling.sirius/target/config.json, instances/modeling.sirius/target/jenkins/configuration.yml, instances/modeling.sirius/target/jenkins/plugins-list.txt, instances/modeling.sirius/target/jenkins/plugins.log, instances/modeling.sirius/target/k8s/configmap-jenkins-config.yml
Related to https://gitlab.eclipse.org/eclipsefdn/helpdesk/-/issues/4301
=> Add Build Blocker plugin to sirius

instances/modeling.sirius/config.jsonnet, instances/modeling.sirius/target/config.json, instances/modeling.sirius/target/jenkins/plugins-list.txt, instances/modeling.sirius/target/jenkins/plugins.log, instances/modeling.sirius/target/k8s/limit-range.json, instances/modeling.sirius/target/k8s/resource-quotas.json
https://github.com/eclipse-cbi/jiro/pull/349#issuecomment-1954642568
=> Sirius remove Build Blocker Plugin

instances/automotive.mdmbl/jenkins/configuration.yml, instances/automotive.mdmbl/target/jenkins/configuration.yml, instances/automotive.mdmbl/target/k8s/configmap-jenkins-config.yml, instances/automotive.mdmbl/target/k8s/limit-range.json, instances/automotive.mdmbl/target/k8s/resource-quotas.json
Related to https://gitlab.eclipse.org/eclipsefdn/helpdesk/-/issues/4349
=> Add mdmbl bot and webhook to gitlab

instances/adoptium.temurin-compliance/jenkins/configuration.yml, instances/adoptium.temurin-compliance/target/jenkins/configuration.yml, instances/adoptium.temurin-compliance/target/jenkins/plugins.log, instances/adoptium.temurin-compliance/target/k8s/configmap-jenkins-config.yml
EF issue: https://gitlab.eclipse.org/eclipsefdn/helpdesk/-/issues/4366
=> ansible: Add jck-azure-ubuntu2204-x64-1 and alpine docker container.

jenkins-create-credentials-token.sh
Related to this comment: https://gitlab.eclipse.org/eclipsefdn/helpdesk/-/issues/4452#note_2136805
=> Change docker credential type in jenkins 

instances/adoptium.temurin-compliance/jenkins/configuration.yml, instances/adoptium.temurin-compliance/target/jenkins/configuration.yml, instances/adoptium.temurin-compliance/target/jenkins/plugins.log, instances/adoptium.temurin-compliance/target/k8s/configmap-jenkins-config.yml
=> ansible: Update key for jck-azure-ubuntu2204-x64-1

instances/adoptium.temurin-compliance/jenkins/configuration.yml, instances/adoptium.temurin-compliance/target/jenkins/configuration.yml, instances/adoptium.temurin-compliance/target/jenkins/plugins.log, instances/adoptium.temurin-compliance/target/k8s/configmap-jenkins-config.yml
EF issue:https://gitlab.eclipse.org/eclipsefdn/helpdesk/-/issues/4760
Already implemented.
=> ansible: Add jck-scaleway-ubuntu2404-2,3

instances/adoptium.temurin-compliance/jenkins/configuration.yml, instances/adoptium.temurin-compliance/target/config.json, instances/adoptium.temurin-compliance/target/jenkins/configuration.yml, instances/adoptium.temurin-compliance/target/jenkins/plugins.log, instances/adoptium.temurin-compliance/target/k8s/configmap-jenkins-config.yml
EF issue: https://gitlab.eclipse.org/eclipsefdn/helpdesk/-/issues/4772#note_2539990
Deployed.
=> Add jck-ubuntu-2204-solaris10 labels.

instances/adoptium.temurin-compliance/jenkins/configuration.yml, instances/adoptium.temurin-compliance/target/jenkins/configuration.yml, instances/adoptium.temurin-compliance/target/k8s/configmap-jenkins-config.yml
EF issue: https://gitlab.eclipse.org/eclipsefdn/helpdesk/-/issues/4737
=> Add jck-skytap-aix72-ppc64-5 machine.

instances/adoptium.temurin-compliance/target/jenkins/configuration.yml, instances/adoptium.temurin-compliance/target/jenkins/plugins.log, instances/adoptium.temurin-compliance/target/k8s/configmap-jenkins-config.yml
Complementary PR for https://github.com/eclipse-cbi/jiro/pull/383
Already reloaded.
=> feat: add extra label for AIX 7.2TL05 system

instances/technology.justj/jenkins/configuration.yml, instances/technology.justj/target/config.json, instances/technology.justj/target/jenkins/configuration.yml, instances/technology.justj/target/jenkins/plugins.log, instances/technology.justj/target/k8s/configmap-jenkins-config.yml
EF issue: https://gitlab.eclipse.org/eclipsefdn/helpdesk/-/issues/5075#note_2831970
=> Add x86_64 label to mp23n-windows-10-label.

instances/automotive.openpass/config.jsonnet, instances/automotive.openpass/target/config.json, instances/automotive.openpass/target/jenkins/configuration.yml, instances/automotive.openpass/target/k8s/configmap-jenkins-config.yml, instances/automotive.openpass/target/k8s/limit-range.json, instances/automotive.openpass/target/k8s/resource-quotas.json, instances/automotive.openpass/target/k8s/statefulset.json, instances/automotive.scm/config.jsonnet, instances/automotive.scm/target/config.json, instances/automotive.scm/target/jenkins/configuration.yml, instances/automotive.scm/target/k8s/configmap-jenkins-config.yml, instances/automotive.scm/target/k8s/limit-range.json, instances/automotive.scm/target/k8s/resource-quotas.json, instances/automotive.scm/target/k8s/statefulset.json
Related to https://gitlab.eclipse.org/eclipsefdn/helpdesk/-/issues/5069
=> Move openpass BMW Group resource packs to automotive.scm

instances/eclipse.platform.releng/jenkins/configuration.yml, instances/eclipse.platform.releng/target/jenkins/configuration.yml, instances/eclipse.platform.releng/target/jenkins/plugins.log, instances/eclipse.platform.releng/target/k8s/configmap-jenkins-config.yml
EF issue: https://gitlab.eclipse.org/eclipsefdn/helpdesk/-/issues/4978#note_2827173
=> Update key for riscv-build2.

instances/adoptium.temurin-compliance/jenkins/configuration.yml, instances/adoptium.temurin-compliance/target/jenkins/configuration.yml, instances/adoptium.temurin-compliance/target/jenkins/plugins.log, instances/adoptium.temurin-compliance/target/k8s/configmap-jenkins-config.yml
EF issue: https://gitlab.eclipse.org/eclipsefdn/helpdesk/-/issues/5104
=> Remove jck-linaru-ubuntu2004-aarch64-2.

instances/technology.omr/jenkins/configuration.yml, instances/technology.omr/target/jenkins/configuration.yml, instances/technology.omr/target/jenkins/plugins.log, instances/technology.omr/target/k8s/configmap-jenkins-config.yml
EF issue: https://gitlab.eclipse.org/eclipsefdn/helpdesk/-/issues/5254
=> technology.omr add riscv64 agent.

instances/technology.omr/jenkins/configuration.yml, instances/technology.omr/target/jenkins/configuration.yml, instances/technology.omr/target/k8s/configmap-jenkins-config.yml
Related to: https://gitlab.eclipse.org/eclipsefdn/it/releng/iac/ansible/-/merge_requests/10
=> Move omr-agent to risc-build1

instances/modeling.xpect/config.jsonnet, instances/modeling.xpect/target/config.json, instances/modeling.xpect/target/jenkins/plugins-list.txt, instances/modeling.xpect/target/jenkins/plugins.log
EF issue: https://gitlab.eclipse.org/eclipsefdn/helpdesk/-/issues/5368
=> Xpect add parameterized-scheduler plugin

instances/technology.omr/jenkins/configuration.yml
Add 3x new Mac 15(2x x86 and 1x aarch64) to OMR Jenkins.
cc: @AdamBrousseau
=> OMR: Add new Mac 15 nodes

instances/eclipse.platform.releng/jenkins/configuration.yml, instances/eclipse.platform.releng/target/jenkins/configuration.yml, instances/eclipse.platform.releng/target/k8s/configmap-jenkins-config.yml, instances/technology.justj/jenkins/configuration.yml, instances/technology.justj/target/jenkins/configuration.yml, instances/technology.justj/target/k8s/configmap-jenkins-config.yml
Configuration already applied to running masters.
=> Move RiscV64 agents from riscv-build1 to riscv-build2

instances/adoptium.temurin-compliance/jenkins/configuration.yml
These VMs were migrated to a new DC which means they have new IP addresses.
=> update IP addresses for SkyTap AIX VMs

instances/technology.omr/jenkins/configuration.yml, instances/technology.omr/target/jenkins/configuration.yml, instances/technology.omr/target/k8s/configmap-jenkins-config.yml
EF issue: https://gitlab.eclipse.org/eclipsefdn/helpdesk/-/issues/5879
=> omr: change ip of riscv-build1 agent.

instances/adoptium.temurin-compliance/jenkins/configuration.yml, instances/adoptium.temurin-compliance/target/jenkins/configuration.yml, instances/adoptium.temurin-compliance/target/k8s/configmap-jenkins-config.yml
EF issue: https://gitlab.eclipse.org/eclipsefdn/helpdesk/-/issues/6107
=> temurin-compliance: Remove decommissioned s390x and ppc64le machines.

instances/eclipse.platform.releng/jenkins/configuration.yml, instances/eclipse.platform.releng/target/jenkins/configuration.yml, instances/eclipse.platform.releng/target/k8s/configmap-jenkins-config.yml
Related to: https://gitlab.eclipse.org/eclipsefdn/helpdesk/-/issues/6260
=> Update ssh-key for releng riscv.

instances/eclipse.platform.releng/jenkins/configuration.yml, instances/eclipse.platform.releng/target/jenkins/configuration.yml, instances/eclipse.platform.releng/target/k8s/configmap-jenkins-config.yml
EF issue: https://gitlab.eclipse.org/eclipsefdn/helpdesk/-/issues/6260
=> releng: move riscv64 from riscv-build1 to riscv-build3.

instances/adoptium.temurin-compliance/jenkins/configuration.yml, instances/adoptium.temurin-compliance/target/config.json, instances/adoptium.temurin-compliance/target/jenkins/configuration.yml, instances/adoptium.temurin-compliance/target/k8s/configmap-jenkins-config.yml
EF issue: https://gitlab.eclipse.org/eclipsefdn/helpdesk/-/issues/6330
=> temurin-compliance: change labels for win11-x64-4cpu-Of4shu

instances/adoptium.temurin-compliance/jenkins/configuration.yml, instances/adoptium.temurin-compliance/target/config.json, instances/adoptium.temurin-compliance/target/jenkins/configuration.yml, instances/adoptium.temurin-compliance/target/k8s/configmap-jenkins-config.yml, templates/jenkins/configuration.yml.hbs
=> temurin-compliance: Replace equinix-ubuntu2004 with equinix-ubuntu2404.

instances/adoptium.temurin-compliance/jenkins/configuration.yml, instances/adoptium.temurin-compliance/target/jenkins/configuration.yml, instances/adoptium.temurin-compliance/target/k8s/configmap-jenkins-config.yml
EF: issue: https://gitlab.eclipse.org/eclipsefdn/helpdesk/-/issues/6339#note_4313198
=> temurin-compliance: replace uk4gcu, remove Jfd4ds

instances/adoptium.temurin-compliance/jenkins/configuration.yml, instances/adoptium.temurin-compliance/target/jenkins/configuration.yml, instances/adoptium.temurin-compliance/target/k8s/configmap-jenkins-config.yml
EF issue: https://gitlab.eclipse.org/eclipsefdn/helpdesk/-/issues/6443
=> temurin-compliance: reinstall jck-scaleway-ubuntu2404-riscv64-3

instances/adoptium.temurin-compliance/jenkins/configuration.yml, instances/adoptium.temurin-compliance/target/jenkins/configuration.yml, instances/adoptium.temurin-compliance/target/k8s/configmap-jenkins-config.yml
EF issue: https://gitlab.eclipse.org/eclipsefdn/helpdesk/-/issues/6514
=> temurin-compliance: migrate from equinix to osusl

instances/ee4j.openmq/jenkins/configuration.yml, instances/ee4j.openmq/target/jenkins/configuration.yml, instances/ee4j.openmq/target/k8s/configmap-jenkins-config.yml
Add env var for Central URL API to OpenMQ (see PR #477)
=> Follow up to PR #477

instances/adoptium.temurin-compliance/jenkins/configuration.yml, instances/adoptium.temurin-compliance/target/config.json, instances/adoptium.temurin-compliance/target/jenkins/configuration.yml, instances/adoptium.temurin-compliance/target/k8s/configmap-jenkins-config.yml
Related to: https://gitlab.eclipse.org/security/vulnerability-reports/-/issues/302
This PR will probably be refined as it picked some changes from commit https://github.com/eclipse-cbi/jiro/commit/9a0b059775e9db037e30a822a03895e06949b442
=> Change access type to skytap servers.
