eclipse-cbi/jiro

instances/technology.openj9/jenkins/plugins-list
- Required for readProperties step
- Used in Check_AIX_PDP_VPN job
Signed-off-by: Adam Brousseau <adam.brousseau@ca.ibm.com>
=> OpenJ9: Add plugin pipeline-utility-steps

instances/technology.openj9/jenkins/plugins-list
- Required to run groovy script post build
that generates a build summary html table.
=> OpenJ9 Add Plugin Groovy-Postbuild

instances/technology.openj9/jenkins/configuration.yml
- Needed to use the GH Commit Status Setter feature
=> OpenJ9 Add config for Github Plugin

instances/technology.openj9/jenkins/plugins-list
- Needed to help identify builds when launched by users (Grinders etc)
=> OpenJ9: Add BuildUser plugin

templates/jenkins/configuration.yml.hbs
See https://github.com/jenkinsci/git-client-plugin/blob/master/src/main/java/hudson/plugins/git/GitTool.java#L51
Related discussion: https://bugs.eclipse.org/bugs/show_bug.cgi?id=550075
=> Use "Default" as name to set default git installation

instances/technology.openj9/jenkins/configuration.yml
Currently the only Aarch64 machine is not able to compile tests, but the
testing label is being added to allow for the option of testing in the
future. The aarch64_linux and aarch64_linux_xl platforms are not included
in the target 'all', and therefore will not be run during the nightly
builds.
Signed-off-by: Colton Mills <millscolt3@gmail.com>
=> Added test label to Aarch64 machine

templates/jenkins/configuration.yml.hbs
version 1.25, which leads to a JCasC error during startup
=> adminAddress field has been marked as deprecated in Mailer plugin

templates/jenkins/partials/tools-maven.hbs
Maven 3.6.2 is now available [1] and fixes the issues with Tycho builds
which were reported by many Eclipse projects, see bug 546463.
[1] https://maven.apache.org/docs/3.6.2/release-notes.html
Bug: 546463
Signed-off-by: Matthias Sohn <matthias.sohn@sap.com>
=> Update Maven 3.6.x to 3.6.2

build/gen-k8s.sh, build/k8s-deploy.sh, templates/default.json.hbs, templates/k8s/m2-dir.yml.hbs, templates/k8s/m2-secret-dir.yml.hbs
This fixes the issue that projects can't deploy to repo.eclipse.org or
OSSRH from the default pod templates.
toolchains.xml is still kept in m2-dir config map.
settings-security.xml is pre-filled with a XML header only.
=> Use m2-secret-dir secret by default instead of configmap

instances/modeling.emf.mwe/jenkins/plugins-list
The MWE build needs parametrized cron triggers.
Signed-off-by: Karsten Thoms <karsten.thoms@itemis.de>
=> [emft.mwe] Add parameterized-scheduler plugin

instances/technology.openj9/jenkins/configuration.yml
- Machines are still being configured and are
failing when compiles land on them.
=> Temporarily remove build label form aix 5,6

instances/technology.openj9/jenkins/configuration.yml
\t is interpreted as a tab in the jenkins configuration
TEMP was added by https://github.com/eclipse-cbi/jiro/pull/80, which breaks all the Windows Nodes.
=> OpenJ9: Fix TEMP env var for Windows

instances/technology.openj9/jenkins/configuration.yml
These machines will need to be disabled once the change is deployed as there is a corresponding change that needs to also merge at eclipse/openj9 before they can be made active.
fyi @pshipton 
EDIT: this is the OpenJ9 dependent PR that needs to go second.
https://github.com/eclipse/openj9/pull/8601
=> OpenJ9: RH7 s390 and AIX machine updates

templates/k8s/statefulset.libsonnet
-Dorg.csanchez.jenkins.plugins.kubernetes.pipeline.PodTemplateStepExecution.defaultImage
Error was:
ERROR: Unable to pull Docker image "basic-agent:3.35".
Check if image tag name is spelled correctly.
=> Fix issue with missing repository name for defaultImage

instances/technology.openj9/jenkins/configuration.yml
* remove build and test labels from old AIX machines
=> OpenJ9: Add build and test labels to new AIX machines

instances/technology.openj9/jenkins/configuration.yml
* eclipse/openj9#8849
* ub16x64j99 and ub16x64j910 soon to be ub18-x86-1 and ub18-x86-2
* ub16-390-3 and ub16-390-4 soon to be ub18-390-1 and ub18-390-2
* ub16p8j95 and ub16p8j96 soon to be ub18-ppcle-1 and ub18-ppcle-2
* remove build label from all
=> OpenJ9: Migrate nodes to ubuntu18

instances/iot.ditto/jenkins/configuration.yml, instances/iot.ditto/jenkins/plugins-list
Hi,
today was the first time we tried to release our JavaScript client since we switched to a jiro instance. We noticed, that we're missing the Pipeline utility steps plugin and configuration for the Git plugin. I added both in this PR.
=> [iot.ditto] Add pipeline utility steps plugin and configure Git plugin

templates/jenkins/configuration.yml.hbs
`instanceCap` will limit the number of concurrently running pod templates even if `containerCapStr` is higher.  `instanceCap` can never exceed `containerCapStr` though. So it should be either set to the same value as `containerCapStr` or not be set at all.
See https://bugs.eclipse.org/bugs/show_bug.cgi?id=563363 for an example
where this caused issues.
=> instanceCap should not be set, setting containerCapStr should be enough

templates/k8s/statefulset.libsonnet
Master pods should not be scheduled on nodes with label "speed=fast".
=> Add node affinity for Jenkins master instances

instances/foundation-internal.webdev/config.jsonnet, instances/foundation-internal.webdev/target/config.json, instances/foundation-internal.webdev/target/jenkins/configuration.yml, instances/foundation-internal.webdev/target/k8s/configmap-jenkins-config.yml, templates/clouds.libsonnet, templates/config.libsonnet
Defining the special namespace also for the agents seems to do the trick. Not sure if this is the most elegant solution. ;)
The same change (or another solution also needs to be applied for the infra JIPP (and any other JIPP with a special namespace).
=> Fix for namespace issue with webdev JIPP

incubation/open_jipps_in_browser.sh
* Support macOS (open vs xdg-open)
* Less heuristics for URL, read and filter the  instance config
* Happy shellchecks
=> Improved open_jipps_in_browser.sh

instances/eclipse.jdt/jenkins/plugins-list
Bug: https://bugs.eclipse.org/bugs/show_bug.cgi?id=565280
Signed-off-by: Roland Grunberg <rgrunber@redhat.com>
=> Add 'warnings' plugin to JDT JIPP plugin configuration.

instances/iot.kuksa/jenkins/plugins-list
Add cobertura plugin to Eclipse kuksa  CI to enable code coverage tests in https://github.com/eclipse/kuksa.val/pull/85
=> Add cobertura plugin for code coverage

instances/technology.openj9/jenkins/configuration.yml
* worker-3 system needs to be used exclusively for artifactory activities
=> OpenJ9: Change labels on worker-3

instances/modeling.tmf.xtext/config.jsonnet
We would like to use the current user for committing automatic changes triggered by releng jobs. Currently we enter that by parameters.
Signed-off-by: Karsten Thoms <karsten.thoms@karakun.com>
=> [Xtext] Add build-user-vars-plugin

instances/technology.openj9/jenkins/configuration.yml
Instead of 'Only build jobs with label
expressions matching this node' change
to 'Use this node as much as possible'.
This change was triggered because the test
jobs in post-parallel step now look for
'any' node. Which means they won't land on
any EXCLUSIVE node. The jobs have started
triggering the kubernetes cloud agents
to be provisioned.
Note: I left aarch64 as is because we only
have one machine for that platform.
=> Change all nodes to mode NORMAL

instances/iot.ditto/jenkins/configuration.yml
Updates the installed NodeJs version as a) the Ditto JavaScript client build requires features of NodeJs > 10 and b) NodeJs 10 has its maintenance EOL end of this month.
=> [iot.ditto] Update installed NodeJs version

instances/adoptium.temurin-compliance/jenkins/configuration.yml
Currently does not have valid `credentialsId` fields but these can hopefully be added by the maintainers when available ;-)
Signed-off-by: Stewart X Addison <sxa@redhat.com>
=> Add initial set of machines for the temurin-compliance project

instances/adoptium.temurin-compliance/jenkins/configuration.yml
Fixes: 
```bash
bash-3.2# ssh -T git@github.com
Client and server could not agree on a key exchange algorithm:
client: diffie-hellman-group-exchange-sha1,diffie-hellman-group14-sha1,diffie-hellman-group1-sha1
server: curve25519-sha256,curve25519-sha256@libssh.org,ecdh-sha2-nistp256,ecdh-sha2-nistp384,ecdh-sha2-nistp521,diffie-hellman-group-exchange-sha256
```
=> Solaris set GIT_SSH to use OpenCSW version of openssh

instances/adoptium.temurin-compliance/jenkins/configuration.yml
the test scripts need `psrinfo` which is in /usr/sbin
=> add /usr/sbin to PATH on Solaris

instances/technology.omr/config.jsonnet
It is expected by https://github.com/eclipse/omr/README.md.
=> Add embeddable-build-status plugin to OMR

instances/adoptium.temurin-compliance/jenkins/configuration.yml
Add first linux/aarchj64 machine to Termurin Compliance server.
=> Add Linux/aarch64 machine to temurin compliance

instances/ecd.theia/config.jsonnet
For https://github.com/eclipse-theia/theia-blueprint/issues/163 we would like to show a status badge for builds on the Github page. 
Therefore we would like to install the "embeddable-build-status" plugin
=> Add embeddable-build-status for Theia

instances/technology.omr/jenkins/configuration.yml
Allows SSH key with passphrases to be used on z/OS nodes
eclipse/omr#6291
https://gitlab.eclipse.org/eclipsefdn/helpdesk/-/issues/745
=> Add java property to z/OS node launch command

instances/adoptium.temurin-compliance/jenkins/configuration.yml
Existing groovy scripts and many other Jenkins servers using said groovy scripts use the name 'openjdk-jenkins-helper'
Change name in config here to match.
Signed-off-by: Shelley Lambert <slambert@gmail.com>
=> Change name to match other Jenkins config

README.md
yq tool repository seems to have change, the original link show a 404 page.
=> docs: change link to yq tool repository

instances/foundation-internal.webdev/jenkins/configuration.yml
Fix for https://github.com/openhwgroup/openhwgroup.org/pull/520. Note that the runtime configuration has already been edited via the UI.
=> Update default version of jenkins-pipeline-library

instances/adoptium.temurin-compliance/jenkins/configuration.yml, instances/adoptium.temurin-compliance/target/jenkins/configuration.yml, instances/adoptium.temurin-compliance/target/k8s/configmap-jenkins-config.yml
Removes jck-marist-rhel7-s390x-1, jck-marist-ubuntu2004-s390x-1, jck-marist-ubuntu2004-s390x-2 nodes. EF issue #2214 https://gitlab.eclipse.org/eclipsefdn/helpdesk/-/issues/2214
=> Decommissioning of old Marist s390x systems

instances/adoptium.temurin-compliance/jenkins/configuration.yml, instances/adoptium.temurin-compliance/target/jenkins/configuration.yml, instances/adoptium.temurin-compliance/target/k8s/configmap-jenkins-config.yml
Agent jck-equinix-containerized-ubuntu2004-aarch32-1 updgrading to JDK-11
Issue https://gitlab.eclipse.org/eclipsefdn/helpdesk/-/issues/2354
=> jck-equinix-containerized-ubuntu2004-aarch32-1 updgrading to JDK-11

instances/technology.omr/jenkins/configuration.yml
Replace win2012-x86-2 with Windows 2019
and rename it win2019x64-openj9-1.
Add another machine to the pool: win2019x64-openj9-2
Signed-off-by: Violeta Sebe <vsebe@ca.ibm.com>
=> Update OMR Windows machines

instances/adoptium.temurin-compliance/jenkins/configuration.yml
temurin-compliance test pipeline architecture requires a "worker" labelled node to best optimize end of test artifact archiving, without it large backlogs can build during release testing.
mythicbeasts-mvyo8-debian10-aarch32 is currently disconnected due to insufficient inodes, but would be ideal as the "worker" node.
This PR removes "ci.role.test" (so that no tests try to run on it), and adds "worker".
Signed-off-by: Andrew Leonard <anleonar@redhat.com>
=> [temurin-compliance] Remove ci.role.test and add worker label to mythicbeasts-mvyo8-debian10-aarch32

instances/eclipse.platform.releng/jenkins/configuration.yml
As part of https://gitlab.eclipse.org/eclipsefdn/helpdesk/-/issues/2448 systematically named labels are added to those agents that are capable to build the SWT native binaries for a certain platform. The label name indicates for which platform the natives can be build by the agent and therefore allow their use in a Jenkins matrix stage.
I added the labels based on the current configuration of the jobs in https://ci.eclipse.org/releng/view/SWT%20Natives/.
@fredg02 can you please review and merge this.
=> Create 'swt.natives' labels for eclipse.platform.releng Jenkins agents

instances/eclipse.platform.releng/jenkins/configuration.yml
In the releng JIPP, the SWT-natives for macosx.aarch64 can currently not be build on the 'b9h15-macos10.15' machine but only on the 'nc1ht-macos11-arm64'.
Part of https://gitlab.eclipse.org/eclipsefdn/helpdesk/-/issues/2448 and required for https://github.com/eclipse-platform/eclipse.platform.swt/pull/514
As told in https://github.com/eclipse-platform/eclipse.platform.swt/pull/514#issuecomment-1408672288 both mac-machines should be fine (although only the setup created with this PR works).
As suggested in https://github.com/eclipse-platform/eclipse.platform.swt/pull/514#issuecomment-1409263936 this moves the labels accordingly.
@fredg02 can you please review and deploy this?
FXI @sravanlakkimsetti
=> Move 'swt.natives'-label for mac.aarch64 from b9h15-macos to nc1ht-macos

.gitignore, utils/local_config.sh
If there is missing entries in cbi configuration files, sub script like `local_config.sh` will not report or print errors. 
So the script exit and fail silently.
Ex: missing configuration in my case
"jenkins_login": {
"user": "sebastien.heurtematte@eclipse-foundation.org",
"pw": "XXXXXXXXXXXXXX"
}
Try to run: /jenkins-cli.sh instances/foundation-internal.webdev reload-jcasc-configuration.
=> Local config fails silently

instances/technology.omr/jenkins/configuration.yml
* remove deb10-x64-1 as its dead
* add label "compile:riscv64:cross" to ub20-x64-omr7 and ub20-x64-omr9 ** docker container also has a requirement on cgroup.v2
Unless there is disagreement this can be merged and deployed when possible.  With the existing system being unrecoverable riscv compiles are broken with or without this change.
fyi @babsingh @AdamBrousseau
=> OMR: Update riscv cross-compile machines

instances/technology.jgit/config.jsonnet
The ansicolor plugin adds support for standard ANSI escape sequences, including color, to Console Output. This can improve readability of maven logs when configuring jobs to set `-Dstyle.color=always`.
See https://plugins.jenkins.io/ansicolor/
=> Add the ansicolor plugin to the JGit Jenkins instance

jenkins-cli.sh
Allow to fix directory creation `.cli_temp_dir` on a fresh install and when jenkins-cli.sh is used by another project like ci-admin.
=> .cli_temp_dir creation on fresh install 

instances/technology.omr/jenkins/configuration.yml
In phase2 of upgrading AIX 7.1 -> 7.2, nodes p8-java1-ibm01,02 will be removed from OMR and add to OpenJ9. P.S: nodes p8-java1-ibm11,12 (both AIX7.2) was added before to OMR
=> Move AIX 7.1 machines from OMR to OpenJ9

build/gen-permissions.sh
According to yq: json format in not part of input value
I get this error n a jiro build: 
```
Error: unknown format 'json' please use [yaml|xml|props]
[2023-12-11 11:40:24][FATAL ][build-image.sh:34 ] Unexpected error (exit code: 1)
```
My local yq version: 4.25.1
Latest yq version: 4.40.4
https://github.com/mikefarah/yq/tree/v4.40.4
```
-p, --input-format string           [yaml|y|xml|x] parse format for input. Note that json is a subset of yaml. (default "yaml")
```
=> yq unknown input format json

instances/adoptium.temurin-compliance/target/jenkins/plugins-list.txt
Add view-job-filters plugin to be able to create a Jenkins view of failing test jobs only.
=> Add view-job-filters plugin to temurin-compliance instance

jenkins-create-credentials-token.sh
Use new entries for quay.io credential: robot-username and robot-token
Related to: https://gitlab.eclipse.org/eclipsefdn/helpdesk/-/issues/3135
=> fix quay.io credentialsId

instances/eclipse.platform.releng/jenkins/configuration.yml
Now that not only SWT but also Equinox uses the specialized build agents to build native binaries (see https://github.com/eclipse-equinox/equinox/pull/603) it would be good to generalize the labels that indicate which node can be used to build for which platform.
=> Add generalized native-builder node labels

templates/jenkins/configuration.yml.hbs
This allow to merge yaml definition from a JenkinsFile
E.g: 
```yaml
pipeline {
agent {
kubernetes {
inheritFrom 'centos-8'
yaml """
spec:
containers:
- name: jnlp
resources:
limits:
memory: "3Gi"
cpu: "2000m"
requests:
memory: "3Gi"
cpu: "2000m"
"""
}
}
stages {
stage('Main') {
steps {
sh 'hostname'
}
}
}
}
```
According to this issue: https://issues.jenkins.io/browse/JENKINS-70061, webui configuration always overrides yaml configuration.
=> Override cpu/memory request and limit from jenkinsfile

templates/clouds.libsonnet, templates/jenkins/configuration.yml.hbs
The default merge strategy for yaml definition in podtemplate is `override`. 
Define specific values in podtemplate with inherit keyword lose all predefined mount volumes. 
Change the yaml merge strategy to `merge`.
See comment here: https://github.com/eclipse-platform/eclipse.platform.releng.aggregator/pull/2149#issuecomment-2190033142
=> Change yaml merge strategy to `merge` for pod template

instances/eclipse.equinox/config.jsonnet, instances/eclipse.equinox/jenkins/configuration.yml, instances/eclipse.platform.releng/config.jsonnet, instances/eclipse.platform.releng/jenkins/configuration.yml, instances/eclipse.platform/config.jsonnet, instances/eclipse.platform/jenkins/configuration.yml
Besides linking the 'jenkins/configuration.yml' to the eclipse.platform and equinox JIPP, this introduce the placeholder `&&INSTANCE_NAME&&` which is replaced with the project's full name while building images.
In this case this is used to ensure different workspace locations for the different JIPPs that use the native nodes.
Required for https://gitlab.eclipse.org/eclipsefdn/helpdesk/-/issues/4231
Instead of introducing a new placeholder `&&INSTANCE_NAME&&`, maybe `{{this.project.fullName}}` could be used instead with the existing templating mechanism?
But I was unable to test that since I failed to setup a functioning CI pipeline that successfully run `make image_eclipse.platform`.
One problem was the installation of an alternative hbs-cli version that does not suffer from …
=> Link native build nodes into eclipse.platform and equinox JIPP

instances/adoptium.temurin-compliance/jenkins/configuration.yml
Adding label so the correct machine can be selected that can run JDK22+
=> feat: add extra label for AIX 7.2TL05 system

build/gen-jenkins.sh
Add a link in the header to the JIRO repository specifically the instance configuration as code. 
This aims to help projects understand their instance is configured as code, and even if they are not admin, they can access some configuration data. 
With the existing instances, the file `/userContent/theme/title.js` has to be removed from the storage.
ref: https://gitlab.eclipse.org/eclipsefdn/helpdesk/-/issues/4784#note_2545026
=> Add a JIRO link in the header with a link to the jiro github repo

instances/technology.omr/jenkins/configuration.yml
Required for Jenkins LTS upgrade to 2.479.1
=> OMR: Update to jdk17 for remoting.jar

instances/technology.omr/jenkins/configuration.yml
Issue runtimes/infrastructure 9263
=> OMR: Add new zos 3.1 systems

instances/technology.omr/jenkins/configuration.yml
- remove 3x old x86 Mac Machines: osx1014-unb-01, mac10-x64-omr1, mac10-x64-omr2
Signed-off-by: Aswin K R <aswinkr77@gmail.com>
Provided 2x Mac 15 in place of these old machines: https://github.com/eclipse-cbi/jiro/pull/433
cc: @AdamBrousseau
=> OMR: Remove old x86 Mac Machines

instances/ecd.theia/config.jsonnet
In order to make the build more stable we want to split the build into different parts, securing the in between states using artifacts.
With this plugin we want to retrieve the artifact from the previous step.
=> Add copyartifact plugin

templates/config.libsonnet
Add a new entry in settings.xml with the server ID: central.
The username and password are token-based and are generated from Central Portal account.
=> Central serverId entry in settings.xml for the OSSRH migration

instances/technology.justj/jenkins/configuration.yml, instances/technology.justj/target/config.json, instances/technology.justj/target/jenkins/configuration.yml, instances/technology.justj/target/k8s/configmap-jenkins-config.yml, instances/technology.omr/jenkins/configuration.yml, instances/technology.omr/target/config.json, instances/technology.omr/target/jenkins/configuration.yml, instances/technology.omr/target/k8s/configmap-jenkins-config.yml
Related to: https://gitlab.eclipse.org/eclipsefdn/helpdesk/-/issues/6626
=> omr, justj: move from riscv-build1 to scaleway-riscv-build3

instances/eclipse.platform.releng/jenkins/configuration.yml
The static JDK, Maven and ANT tools are outdated and not used. For some (i.e. ANT) dynamically installed alternative exists, that are better to use.
Relates to
- https://gitlab.eclipse.org/eclipsefdn/helpdesk/-/issues/6653
@fredg02, @heurtematte or @pstankie could you please review and apply this ASAP as the Windows node is currently broken, because it tries to use the already removed ANT installation
=> Remove outdated tools from permanent nodes in RelEng instance
